### ISSUE TITLE
Problem with Date and equals method

### ISSUE THREAD

**Issue by antonioalonzi** [shazam/shazamcrest#21]
Hi guys,

I discovered a problem with how Date objects are compared by the sameBeanAs() method.

Basically, to compare two Date objects, sameBeanAs() uses the toString() method and then compare them as String.
Now Date objects contains as well milliseconds but the toString() method prints the Date only up to the second.

Example:

```
@Test
    public void shazamDateProblem() throws InterruptedException {
        Person first = new Person("first", new Date());
        Thread.sleep(10);
        Person firstCopy = new Person("first", new Date());

        // this should fail as the two dates are different
        assertThat(first, sameBeanAs(firstCopy));
        System.out.println("are dates equals? " + first.dateOfBirth.equals(firstCopy.getDateOfBirth()));

        // this test will be pass most of the time but will fail sometimes
        // run shazamDateProblemRepeated
    }

    @Test
    public void shazamDateProblemRepeated() throws InterruptedException {
        for (int i = 0; i < 100; i++) {
            shazamDateProblem();
        }
    }

    public static class Person {
        private String name;
        private Date dateOfBirth;

        public Person(String name, Date dateOfBirth) {
            this.name = name;
            this.dateOfBirth = dateOfBirth;
        }

        public String getName() {
            return name;
        }

        public Date getDateOfBirth() {
            return dateOfBirth;
        }

```

In the example above the *shazamDateProblem()* will pass most of the time and fail very rarely.
(run shazamDateProblemRepeated() to see the failure happening always).

Although *shazamDateProblem()* is a bad test, I really think shazamcrest library should check milliseconds and fail the test.
So the developer, seeing the failing test, can decide what to do:
 - fake Date using org.joda.time.DateTimeUtils.setCurrentMillisFixed()
 - ignore the Date field
 - any other way the developer want it to handle

And not having a test that sometimes will fail because the developer did not realize that his domain class contained a Date.

**Comment by Jarcionek** [comment]
Opened a pull request #22 with a fix

**Comment by lucanaldini** [comment]
Thanks @Jarcionek for the pull request. That has been merged now.
